import random
import sys

class Computer:	# If user chosee '1', computer will generate a number and user will be guess it. 

	def __init__(self): 	 		
		guest, number_of_computer = self.guess_start(self.generate_number())
		self.calculate(guest, number_of_computer)
		
	def generate_number(self): # Its checked whether if the number produced by the COMPUTER with have "different digits" in this function.

		while True:
			number_of_computer = str(random.randint(1000,9999))
			unique_list = []				# The random generated number is checked with an empty list.
			for i in number_of_computer:
				if i not in unique_list:
					unique_list.append(i)	# Each digit that is different is appended to the empty list.

			if len(unique_list) == 4:	# Thus, if the length of the empty list is equal to 4, we can say; "the digits of the generated number are different".
				break
		return number_of_computer

	def guess_start(self, number_of_computer):

		# print("number generated by the computer: {}".format(number_of_computer))	# to print the number generated by the computer		
		guess = input("please, enter a 4-digit number with different digits...\n")
		while True:
			different_list = [] # At line that from 28 to 32, its checked whether if the number produced by the USER with have "different digits" in this function.
			for i in guess:
				if i not in different_list:
					different_list.append(i)	# Each digit that is different is appended to the empty list.
			if len(different_list)==4 and len(guess)==4 and guess.isdigit():  # The user was prevented from entering a format other than a 4-digit integer number.
				if guess==number_of_computer:
					print("perfect! your guess is true :) \n")
					sys.exit()
				else:			
					# print("number generated by the computer: {}".format(number_of_computer)) # to print the number generated by the computer
					print("\n")
					self.calculate(guess, number_of_computer)
					print("sorry, your guess is false :(")
					guess = input("please, enter again a 4-digit number with different digits...\n")
			else:
				guess = input("please, only enter a 4-digit number with different digits...\n")		
			
		return guess, number_of_computer

	def calculate(self, guess, number_of_computer): # Its calculate whether if guess is true.

		positive_count=0
		negative_count=0
		for i in range(4):
			if guess[i]==number_of_computer[i]: # If there are same digits on the estimated  number with generated number by computer and its in the correct places
				positive_count +=1					
			else:
				for k in range(4):
					if guess[i]==number_of_computer[k]: # If there are same digits on the estimated  number with generated number by computer,but its in the wrong places
						negative_count +=1								

		if positive_count!=0:
			print("+{}".format(positive_count))
		if negative_count!=0:
			print("-{}".format(negative_count))

class User(object):	# If user chosee '2', user will think a number and computer  will be guess it.

	def __init__(self, c, w):  
		print(" ==============================================\n \
Please, think of a 4-digits integer number from 1000 to 9999 and \n \
I will try to guess it. After each guess, I will ask you if it is \n \
your number or for your hint. You should respond '+(your_value)' \n \
or  '-(your_value)' as a hint. \n \
==============================================\n ") 
		self.calculate_(c, w)

	def isUniq(self, i):	# Its checked whether if the number produced by the COMPUTER with have "different digits" in this function.
		a=i%10
		b=int(i/10)%10
		c=int(i/100)%10
		d=int(i/1000)
		return (a!=b) and (a!=c) and (a!=d) and (b!=c) and (b!=d) and (c!=d)

	def getCW(self, i, j):	 # It is checking c and w walue that is belong to computer's guess
		c = 0
		w = 0
		x1 = int(i) % 10
		x2 = int((i / 10)) % 10
		x3 = int((i / 100)) % 10
		x4 = int(i / 1000)
		y1 = int(j % 10)
		y2 = int((j / 10)) % 10
		y3 = int((j / 100)) % 10
		y4 = int(j / 1000)
		if (x1 == y1):
			c=c+1 
		elif (x1 == y2 or x1 == y3 or x1 == y4):
			w=w+1
		if (x2 == y2):
			c=c+1
		elif (x2 == y1 or x2 == y3 or x2 == y4):
			w=w+1
		if (x3 == y3):
			c=c+1
		elif (x3 == y1 or x3 == y2 or x3 == y4):
			w=w+1
		if (x4 == y4):
			c=c+1
		elif (x4 == y1 or x4 == y2 or x4 == y3):
			w=w+1
		return c,w
  
	def calculate_(self, c, w): # Its calculate whether if guess is true.
		origin = []
		for i in range (1000,9999): 
			if self.isUniq(i):
			  origin.append(i)	# If the values generated by the computer have different digits, this line is initially appended to this values into the list named "origin".
		while(c!=4):
			guess_of_computer = random.choice(origin)
			print("my guess is : {} \n".format(guess_of_computer)) # It takes hints that given by user
			c = int(input("Correct: "))
			w = int(input("Wrong: "))	
			temp = [] 
			for i in origin:
			  C, W = self.getCW(guess_of_computer,i)
			  if (C==c and W==abs(w)):	# If user's hint is into the list with named 'origin', It is appended to a new temporary list.
			    temp.append(i)
			origin = temp
			if len(origin)==0 or c<0 or w>0:  # The user was prevented from entering a format other than a logical value.
				print("You made the wrong typing or logical fault. Please try again....\n") 
				sys.exit()
		if c == 4:
			print("\nfinally!, I found the number that you thought !!!") # when correct value is found, this line will be executed 
			print("\nYour number is {} \n".format(guess_of_computer))

if __name__ == '__main__':
	print(" ==============================================\n \
Heyy, Welcome to the number guessing game!...\n \
Do you want to guess or should I? \n \
- no, thanks. I will guess (PRESS 1) \n \
- yesss, please make guess (PRESS 2) \n \
==============================================\n")	# game set up
	while True:
		choice = input()
		if choice == '1':	# If user chosee '1', computer will generate a number and user will be guess it. 
			Computer()
			break
		elif choice == '2':
			User(0, 0) 	# If user chosee '2', user will think a number and computer  will be guess it. # c=0, w=0
			break
		else:					# on the other different entering by user
			print("\n ==============================================\n \
You made the wrong choice. Please try again....\n \
Do you want to guess or should I? \n \
- no, thanks. I will guess (PRESS 1) \n \
- yesss, please make guess (PRESS 2) \n \
==============================================\n")