import random
import sys

class Computer:	#If user chosee '1', computer will generate a number and user will be guess it. 

	def __init__(self): 	 		
		guest, number_of_computer = self.guess_start(self.generate_number())
		self.calculate(guest, number_of_computer)
		
	def generate_number(self): #Its checked whether if the number produced by the COMPUTER with have "different digits" in this function.

		while True:
			number_of_computer = str(random.randint(1000,9999))
			unique_list = []				#The random generated number is checked with an empty list.
			for i in number_of_computer:
				if i not in unique_list:
					unique_list.append(i)	#Each digit that is different is appended to the empty list.

			if len(unique_list) == 4:	#Thus, if the length of the empty list is equal to 4, we can say; "the digits of the generated number are different".
				break
		return number_of_computer

	def guess_start(self, number_of_computer):

		#print("number generated by the computer: {}".format(number_of_computer))	#to print the number generated by the computer		
		guess = input("please, enter a 4-digit number with different digits...\n")
		while True:
			different_list = [] #At line that from 28 to 32, its checked whether if the number produced by the USER with have "different digits" in this function.
			for i in guess:
				if i not in different_list:
					different_list.append(i)	#Each digit that is different is appended to the empty list.
			if len(different_list)==4 and len(guess)==4 and guess.isdigit():  #The user was prevented from entering a format other than a 4-digit integer number.
				if guess==number_of_computer:
					print("perfect! your guess is true :) \n")
					break
				else:			
					#print("number generated by the computer: {}".format(number_of_computer)) #to print the number generated by the computer
					print("\n")
					self.calculate(guess, number_of_computer)
					print("sorry, your guess is false :(")
					guess = input("please, enter again a 4-digit number with different digits...\n")
			else:
				guess = input("please, only enter a 4-digit number with different digits...\n")		
			
		return guess, number_of_computer

	def calculate(self, guess, number_of_computer): #Its calculate whether if guess is true.

		positive_count=0
		negative_count=0
		for i in range(4):
			if guess[i]==number_of_computer[i]: #If there are same digits on the estimated  number with generated number by computer and its in the correct places
				positive_count +=1					
			else:
				for k in range(4):
					if guess[i]==number_of_computer[k]: #If there are same digits on the estimated  number with generated number by computer,but its in the wrong places
						negative_count +=1								

		if positive_count!=0:
			print("+{}".format(positive_count))
		if negative_count!=0:
			print("-{}".format(negative_count))

class User(object):	#If user chosee '2', user will think a number and computer  will be guess it.

	def __init__(self, mn, mx):  
		print(" ==============================================\n \
Please, think of a 4-digits integer number from 1000 to 9999 and \n \
I will guess it.After each guess, I will ask you if it is less  \n \
than or equalto some number, and you should respond with 'yes',\n \
'no' or 'found'. \n ==============================================\n") 
		self.binarysearch(mn, mx)

	def print(self, mn, mx, guess):	#It tries to find the number that the user thinks using "binary search" method.
		while True:
			s = input("is your guess less or equal %d?  " %guess)
			if s=='yes':
				mx = guess-1	#If user type 'yes', its change local maximum value
				break
			elif s=='no':
				mn = guess+1 	#If user type 'no', its change local minimum value
				break
			elif s=='found':
				print("finally!, I found the number that you thought !!! \n")
				sys.exit()
			else:
				print("please only answer as yes/no' or 'found' \n")
				break
		self.binarysearch(mn,mx)

	def binarysearch(self, mn, mx):
		guess = (mn+mx)/2 if (mn + mx) % 2 == 0 else  (mn + mx + 1)/2
		self.print(mn,mx,guess)

if __name__ == '__main__':
	print(" ==============================================\n \
Heyy, Welcome to the number guessing game!...\n \
Do you want to guess or should I? \n \
- no, thanks. I will guess (PRESS 1) \n \
- yesss, please make guess (PRESS 2) \n \
==============================================\n")	#game set up
	while True:
		choice = input()
		if choice == '1':	#If user chosee '1', computer will generate a number and user will be guess it. 
			Computer()
			break
		elif choice == '2':
			User(1000, 9999) 	#If user chosee '2', user will think a number and computer  will be guess it.
			break
		else:					#on the other different entering by user
			print("\n ==============================================\n \
You made the wrong choice. Please try again....\n \
Do you want to guess or should I? \n \
- no, thanks. I will guess (PRESS 1) \n \
- yesss, please make guess (PRESS 2) \n \
==============================================\n")